
spring:
  datasource:
    #######################\u5E38\u89C4\u914D\u7F6E#######################
    #\u6570\u636E\u5E93\u9A71\u52A8\u7C7B\u540D
    driver-class-name: com.mysql.cj.jdbc.Driver
    #\u6570\u636E\u5E93\u8FDE\u63A5
    url: jdbc:mysql://localhost:3306/stealing_blog_data?useSSL=false&useUnicode=true&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    #\u6570\u636E\u5E93\u7528\u6237\u540D
    username: root
    #\u6570\u636E\u5E93\u5BC6\u7801
    password: root

# Thymeleaf \u6A21\u677F\u914D\u7F6E
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8